import type { Metadata } from "next";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/reusuables";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-auraWhite`}
      >
        <SidebarProvider>
          <AppSidebar />

          <main className="w-full min-h-screen flex flex-col space-y-8">

            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
